/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAnneesRouteImport } from './routes/_app.annees'
import { Route as AppAnneesYearRouteImport } from './routes/_app.annees.$year'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnneesRoute = AppAnneesRouteImport.update({
  id: '/annees',
  path: '/annees',
  getParentRoute: () => AppRoute,
} as any)
const AppAnneesYearRoute = AppAnneesYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => AppAnneesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/annees': typeof AppAnneesRouteWithChildren
  '/annees/$year': typeof AppAnneesYearRoute
}
export interface FileRoutesByTo {
  '/annees': typeof AppAnneesRouteWithChildren
  '/': typeof AppIndexRoute
  '/annees/$year': typeof AppAnneesYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/annees': typeof AppAnneesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/annees/$year': typeof AppAnneesYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/annees' | '/annees/$year'
  fileRoutesByTo: FileRoutesByTo
  to: '/annees' | '/' | '/annees/$year'
  id: '__root__' | '/_app' | '/_app/annees' | '/_app/' | '/_app/annees/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annees': {
      id: '/_app/annees'
      path: '/annees'
      fullPath: '/annees'
      preLoaderRoute: typeof AppAnneesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annees/$year': {
      id: '/_app/annees/$year'
      path: '/$year'
      fullPath: '/annees/$year'
      preLoaderRoute: typeof AppAnneesYearRouteImport
      parentRoute: typeof AppAnneesRoute
    }
  }
}

interface AppAnneesRouteChildren {
  AppAnneesYearRoute: typeof AppAnneesYearRoute
}

const AppAnneesRouteChildren: AppAnneesRouteChildren = {
  AppAnneesYearRoute: AppAnneesYearRoute,
}

const AppAnneesRouteWithChildren = AppAnneesRoute._addFileChildren(
  AppAnneesRouteChildren,
)

interface AppRouteChildren {
  AppAnneesRoute: typeof AppAnneesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnneesRoute: AppAnneesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
