/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppYearsRouteImport } from './routes/_app.years'
import { Route as AppEcolesRouteImport } from './routes/_app.ecoles'
import { Route as AppDestinationsRouteImport } from './routes/_app.destinations'
import { Route as AppAnneesEmployeeIdIndexRouteImport } from './routes/_app.annees.$employeeId.index'
import { Route as AppAnneesEmployeeIdYearRouteImport } from './routes/_app.annees.$employeeId.$year'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppYearsRoute = AppYearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => AppRoute,
} as any)
const AppEcolesRoute = AppEcolesRouteImport.update({
  id: '/ecoles',
  path: '/ecoles',
  getParentRoute: () => AppRoute,
} as any)
const AppDestinationsRoute = AppDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AppRoute,
} as any)
const AppAnneesEmployeeIdIndexRoute =
  AppAnneesEmployeeIdIndexRouteImport.update({
    id: '/annees/$employeeId/',
    path: '/annees/$employeeId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAnneesEmployeeIdYearRoute = AppAnneesEmployeeIdYearRouteImport.update({
  id: '/annees/$employeeId/$year',
  path: '/annees/$employeeId/$year',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/destinations': typeof AppDestinationsRoute
  '/ecoles': typeof AppEcolesRoute
  '/years': typeof AppYearsRoute
  '/annees/$employeeId/$year': typeof AppAnneesEmployeeIdYearRoute
  '/annees/$employeeId/': typeof AppAnneesEmployeeIdIndexRoute
}
export interface FileRoutesByTo {
  '/destinations': typeof AppDestinationsRoute
  '/ecoles': typeof AppEcolesRoute
  '/years': typeof AppYearsRoute
  '/': typeof AppIndexRoute
  '/annees/$employeeId/$year': typeof AppAnneesEmployeeIdYearRoute
  '/annees/$employeeId': typeof AppAnneesEmployeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/destinations': typeof AppDestinationsRoute
  '/_app/ecoles': typeof AppEcolesRoute
  '/_app/years': typeof AppYearsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/annees/$employeeId/$year': typeof AppAnneesEmployeeIdYearRoute
  '/_app/annees/$employeeId/': typeof AppAnneesEmployeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinations'
    | '/ecoles'
    | '/years'
    | '/annees/$employeeId/$year'
    | '/annees/$employeeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/destinations'
    | '/ecoles'
    | '/years'
    | '/'
    | '/annees/$employeeId/$year'
    | '/annees/$employeeId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/destinations'
    | '/_app/ecoles'
    | '/_app/years'
    | '/_app/'
    | '/_app/annees/$employeeId/$year'
    | '/_app/annees/$employeeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/years': {
      id: '/_app/years'
      path: '/years'
      fullPath: '/years'
      preLoaderRoute: typeof AppYearsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecoles': {
      id: '/_app/ecoles'
      path: '/ecoles'
      fullPath: '/ecoles'
      preLoaderRoute: typeof AppEcolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/destinations': {
      id: '/_app/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof AppDestinationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annees/$employeeId/': {
      id: '/_app/annees/$employeeId/'
      path: '/annees/$employeeId'
      fullPath: '/annees/$employeeId/'
      preLoaderRoute: typeof AppAnneesEmployeeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annees/$employeeId/$year': {
      id: '/_app/annees/$employeeId/$year'
      path: '/annees/$employeeId/$year'
      fullPath: '/annees/$employeeId/$year'
      preLoaderRoute: typeof AppAnneesEmployeeIdYearRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDestinationsRoute: typeof AppDestinationsRoute
  AppEcolesRoute: typeof AppEcolesRoute
  AppYearsRoute: typeof AppYearsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnneesEmployeeIdYearRoute: typeof AppAnneesEmployeeIdYearRoute
  AppAnneesEmployeeIdIndexRoute: typeof AppAnneesEmployeeIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDestinationsRoute: AppDestinationsRoute,
  AppEcolesRoute: AppEcolesRoute,
  AppYearsRoute: AppYearsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnneesEmployeeIdYearRoute: AppAnneesEmployeeIdYearRoute,
  AppAnneesEmployeeIdIndexRoute: AppAnneesEmployeeIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
